"""Constants for the Irrigation Addon integration."""

DOMAIN = "irrigation_addon"

# Configuration keys
CONF_ROOMS = "rooms"
CONF_SETTINGS = "settings"

# Default settings
DEFAULT_PUMP_ZONE_DELAY = 3
DEFAULT_SENSOR_UPDATE_INTERVAL = 30
DEFAULT_MANUAL_DURATION = 300
DEFAULT_FAIL_SAFE_ENABLED = True
DEFAULT_EMERGENCY_STOP_ENABLED = True
DEFAULT_NOTIFICATIONS_ENABLED = True
DEFAULT_ERROR_NOTIFICATIONS = True
DEFAULT_LOGGING_LEVEL = "INFO"
DEFAULT_MAX_HISTORY_DAYS = 30
DEFAULT_MAX_DAILY_IRRIGATION = 3600

# Event types
EVENT_TYPE_P1 = "P1"
EVENT_TYPE_P2 = "P2"

# Storage keys
STORAGE_KEY = f"{DOMAIN}_storage"
STORAGE_VERSION = 1